services:
  db:
    image: postgres
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USERNAME: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${PG_PORT}/${PG_DB}
      SPRING_DATASOURCE_USERNAME: ${PG_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update