services:
  db:
    container_name: pg_for_content_app
    image: postgres
    ports:
      - 5437:${PG_PORT}
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${PG_DB}", "-U", "${PG_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: content_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env